### ISSUE TITLE
[Question]: Update TaskAtom from within itself

### ISSUE THREAD

**Issue by riley-usagi** [ra1028/swiftui-atom-properties#149]
### Checklist

- [X] Reviewed the README and documentation.
- [X] Confirmed that this is uncovered by existing docs or examples.
- [X] Checked existing issues & PRs to ensure not duplicated.

### Description

Hello

First of all, I want to express my admiration for this library =)

And secondly, I want to ask, probably, a stupid question on the technical side:

Can you tell me if it's possible to update TaskAtom from within itself without causing the View to constantly refresh and flicker?

For example, I created a very simple example to show the functionality I want to achieve and what came out of it:

https://github.com/user-attachments/assets/7453803c-e64f-47b4-8556-9df49f651531

I guest it might be possible to achieve this using intermediate Atoms or by using ObservableObject, but it doesn't look very elegant.

[Code example](https://github.com/riley-usagi/RickAndMortyViaAtoms)

**Comment by ra1028** [comment]
From what I see, the atoms seem to be functioning properly.
 The cause of that flicker iwould be that you put a bit of delay before the list items are fetched, and apart from that, the view layout is broken during loading.

**Comment by riley-usagi** [comment]
By using **ObjectAtom** instead of **TaskAtoms** I was able to solve the jumping block problem, but it seems a bit overcomplicated.

I guess the problem is in Suspense logic.


https://github.com/user-attachments/assets/c1636813-a827-4a1b-b4f1-f467225ab5d2

**Comment by ra1028** [comment]
Suspense falls back to the specified view during loading. In your case, it's ProgressView, but it resist to be expanded and maintains its own intrinsic size, so try instead to set a view that extend its own size as much as possible, like Spacer for example. 
That should solve the flicker, thus again, it's layout problem.

**Comment by ra1028** [comment]
You might be also interested in the phase modifiers.

https://ra1028.github.io/swiftui-atom-properties/documentation/atoms/throwingtaskatom/phase

**Comment by riley-usagi** [comment]
https://github.com/user-attachments/assets/de47e27e-ffe3-4305-9107-8069998844eb

Even using [AsyncPhase](https://github.com/riley-usagi/RickAndMortyViaAtoms/blob/viaPhase/Api/Atoms/Characters%20atom.swift) i still have the same problem. 

Pay attention to the text field in particular.

At the moment, the only thing that helps to avoid redrawing View is to use `@Published`, but this looks like a overcomplication. =\

---

The main problem with Suspence and AsyncPhase, in my opinion, is that they don't have the functionality to display the previous received value until we get a new one. 

Every time we access Atom, we go through a chain that includes the state - `suspending`.

**Comment by ra1028** [comment]
Again, that text field moving to the center for a moment is a layout issue.
 My comments so far explain how SwiftUI interprets layout, so please check it carefully again.

Also, as you say, TaskAtom returns to the suspending state once on update for consistency, even with the phase modifier.
 For implementations such as continuing to display the previously received value, it fits to use ObservableObjectAtom or to combine multiple atoms and AtomEffects for caching.

It's not in our plan to cover such an extended UX as an architectur library as of now.
